server:
  port: 8080
  servlet:
    path: /*
    contextPath:

flyway:
  enabled: true
  locations: classpath:db/migration
  schemas: [finance_db]

spring:
  boot:
    admin:
      url: http://localhost:8085
      period: 360000
  application:
    name: finance-digital


logging:
  file: target/finance-digital.log
  level:
    org:
      apache: info
      springframework:
        web: info
datasource:
    url: jdbc:h2:mem:finance_db
    username: postgres
    password: postgres
    hibernate:
      hbm2ddl.method: none
      show.sql: true
      dialect: org.hibernate.dialect.H2Dialect

local:
  properties:
    exchangeUri: 'https://api.exchangeratesapi.io/latest?base={baseCode}&symbols={currencyCode}'